services:
  backend:
    build:
      context: .
      dockerfile: URL_Shortener/Dockerfile
    ports:
      - "5049:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Data Source=/app/data/url_shortener.db
    volumes:
      - sqlite_data:/app/data
    restart: always

  frontend:
    build:
      context: ./URL_Shortener/ClientApp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

volumes:
  sqlite_data:
